wrongDataFormat <- "Data format is not valid. \n Either file extension is wrong or data format is not valid."
noDateColumn <- "We assume the dataset you uploaded contains at lease one date time column, but no date time column is identified, please check."
invalidDateFormt <- "Selected date format is not matching with the uploaded file dates."
invalidNewDateFormt <- "New date format is not matching with the first uploaded file date format. New date format should in "
noGageIdFound <- "Enter a gage id"
noGagaDataDownloaded <- "No USGS gage data has been downladed yet!"
calculateDailyStats <- "Please calculate the daily statistics first on the 'Upload Data' tab and select required parameters"
noDaymetDataDownloaded <- "Enter Site Latitude and Longitude values to download dayMet data."
downlaodDaymetData <- "Please download daymet data first."
selectDaymetVars <- "Please select daymet variables to plot"
siteIdNotOne <- "More than one site ID is detected, please confirm if the loaded data is a single site file."
noSiteIdFound <- "No site ID is detected, please confirm if the loaded data has the SiteID column."
homePageStep1Title <- "Step 1: Select parameters to process, date and time column names"