wrongDataFormat <- "Data format is not valid. \n Either file extension is wrong or data format is not valid."
invalidDateFormt <- "Selected date format is not matching with the uploaded file dates."
invalidNewDateFormt <- "New date format is not matching with the first uploaded file date format. New date format should in "
noGageIdFound <- "Enter a gage id"
noGagaDataDownloaded <- "No USGS gage data has been downladed yet!"
calculateDailyStats <- "Please calculate the daily statistics first on the 'Upload Data' tab and select required parameters"
noDaymetDataDownloaded <- "Enter Site Latitude and Longitude values to download dayMet data."
downlaodDaymetData <- "Please download daymet data first."
selectDaymetVars <- "Please select daymet variables to plot"
siteIdNotOne <- "More than one site ID is detected, please confirm if the loaded data is a single site file."
noSiteIdFound <- "No site ID is detected, please confirm if the loaded data has the SiteID column."
homePageStep1Title <- "Step 1: Select parameters to process, date and time column names"
discreteVarMismatch <- "Continuous 'variables to process' and Discrete 'variables to process' are not matching."
csvFileAndExcelissue <- "Warning: Microsoft Excel corrupts .csv file when	 re-imported into Excel.  If you re-open the file by double-clicking its icon or by using the:
File > Open dialog, Excel tries to 'help' you by changing the formats.  You can avoid this by using the Text or Data Import Wizard from the Data Tab.
You can tell the Wizard that the files are Text"
selectBaseVars <- "Please select variables to plot."
selectGageVars <- "Please select USGS gage variables to plot."